server:
  port: 9000
spring:
  application:
    name: gateway
  profiles:
    active: dev
---
spring:
  profiles: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 5d1d5b0f-d00a-43f4-8706-901c97ee698f
    gateway:
      discovery:
        locator:
          #让gateway发现其他微服务组件
          enabled: true
      routes:
         #测试网关配置
#        - id: after_route
#          uri: lb://user-center
#          predicates:
#            # 当且仅当请求时的时间After配置的时间时，才会转发到用户微服务
#            # 目前配置不会进该路由配置，所以返回404
#            # 将时间改成 < now的时间，则访问localhost:8040/** -> user-center/**
#            # eg. 访问http://localhost:9000/users/1 -> user-center/users/1
#            - After=2020-01-20T17:42:47.789-07:00[America/Denver]
        #用户中心网关配置
        - id: user-route
          uri: lb://user-center
          predicates:
            - Path=/users/**
        #内容中心网关配置
        - id: content_route
          uri: lb://content-center
          predicates:
            - Path=/shares/**,/admin/**
  #zipkin
  zipkin:
    #server地址
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #抽样率(100%)
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        #暴露所有端点
        include: '*'
  endpoint:
    health:
      #展示健康详情
      show-details: always
---
spring:
  profiles: prod